-- targets/telemetry/deliver.sql
--
-- Deliver data from source (a telemetry view) to target (a Hive or Kafka sink, depending on configuration)
-- 
-- Substitution parameters:
--   %HOSTNAME%

SET SCHEMA '"SQLstream_Telemetry"';

CREATE OR REPLACE PUMP TELEMETRY_SERVER_PUMP STOPPED
AS
INSERT INTO TELEMETRY_SERVER_SINK
SELECT STREAM '%HOSTNAME%'
     , *
FROM TELEMETRY_SERVER_INFO
;


CREATE OR REPLACE PUMP TELEMETRY_STREAM_GRAPH_PUMP STOPPED
AS
INSERT INTO TELEMETRY_STREAM_GRAPH_SINK
SELECT STREAM '%HOSTNAME%'
     , *
FROM TELEMETRY_STREAM_GRAPH_INFO
;


CREATE OR REPLACE PUMP TELEMETRY_STREAM_OPERATOR_PUMP STOPPED
AS
INSERT INTO TELEMETRY_STREAM_OPERATOR_SINK
SELECT STREAM '%HOSTNAME%'
     , *
FROM TELEMETRY_STREAM_OPERATOR_INFO
;


